### ISSUE TITLE
Question for the method of the Heterogeneous Information Networks' construction

### ISSUE THREAD

**Issue by asjqmasjqm** [BunsenFeng/BotHeterogeneity#2]
hello, thanks for reading my question:
《Heterogeneity-aware Twitter Bot Detection with Relational Graph Transformers》 has mentioned the Heterogeneous Information Networks(relation heterogeneity and influence heterogeneity), but I have not found the method of how to build the Heterogeneous Information Networks(HIN). Can you introduce the details of the method of building the Heterogeneous Information Networks. Thank you very much!

**Comment by TamSiuhin** [comment]
Hi, thanks for your interest! We construct the HIN that has two kinds of relations, follower and following. The source code could be found at [https://github.com/BunsenFeng/BotHeterogeneity/blob/main/data%20process/follower_following_edge.py](https://github.com/BunsenFeng/BotHeterogeneity/blob/main/data%20process/follower_following_edge.py).

**Comment by asjqmasjqm** [comment]
> Hi, thanks for your interest! We construct the HIN that has two kinds of relations, follower and following. The source code could be found at [https://github.com/BunsenFeng/BotHeterogeneity/blob/main/data%20process/follower_following_edge.py](url).
「HIN that has two kinds of relations, follower and following」, the paper say there are "relation and influence heterogeneity", I want to know how to build the heterogenous graph. Thanks.

**Comment by TamSiuhin** [comment]
We had a private communication and solved this problem.
