### ISSUE TITLE
Is the uploaded code incomplete?

### ISSUE THREAD

**Issue by MMMMMz** [BunsenFeng/BotHeterogeneity#3]
Is the uploaded code incomplete?
I haven't seen the code for how so many files are generated.
What part of the experiment are the different files mainly doing?

**Comment by MMMMMz** [comment]
Was the code you uploaded earlier used to generate some user profile file in "BotHeterogeneity"? Such as BotRGCN.
I'm not sure because the generated files are named differently.

**Comment by TamSiuhin** [comment]
Hi, thanks for your interest in our work! We use the same user feature as BotRGCN and the preprocess code to generate the description and tweets embeddings can be found [here](https://github.com/BunsenFeng/BotRGCN/blob/main/Dataset.py). For a more up-to-date implementation of RGT, please refer to our latest work [TwiBot-22](https://github.com/LuoUndergradXJTU/TwiBot-22/tree/master/src/RGT).
