### ISSUE TITLE
Was the code you uploaded earlier used ？

### ISSUE THREAD

**Issue by MMMMMz** [BunsenFeng/BotHeterogeneity#4]
Was the code you uploaded earlier used to generate some user profile file in "BotHeterogeneity"? Such as BotRGCN.
I'm not sure because the generated files are named differently.

**Comment by TamSiuhin** [comment]
Hi, the input feature of BotHeterogeneity is exactly the same as BotRGCN's and we use the same code to preprocess users' features.  The only difference between preprocess file of RGT and BotRGCN is the file name, you can use the code of BotRGCN to generate RGT's input features and change the file name to make the code works.
