### ISSUE TITLE
Missing files while running "allrelation.py"

### ISSUE THREAD

**Issue by bsexpa069380** [BunsenFeng/BotHeterogeneity#5]
After running thorough the data preprocess codes, there seems to be missing some PyTorch files, such as label_list.pt, user_feature2.pt, user_feature3.pt

May I ask if there is some code missing ? If there are some extra data process files, how should I process the data to get the similar results ?

**Comment by TamSiuhin** [comment]
Hi, thanks for your interest in our work! We use the same input features as BotRGCN and you can use the code [here](https://github.com/BunsenFeng/BotRGCN/blob/main/Dataset.py) to generate the preprocess files and change the filename to make the code work. To reproduce the results we reported, please run the TBD.py file😃

**Comment by bsexpa069380** [comment]
Thanks a lot for the reply. I just check out the BotRGCN data process codes. It seems that there are some files are named differently. For example, label.pt –> label_list.pt , tweet_tensor.pt –> user_feature2.pt and num_prop.pt –> user_feature3.pt etc.

May I know if my assumptions are correct ?

**Comment by TamSiuhin** [comment]
There are some differences in the file name, label.pt -> label_list.pt, category_propertities -> My_user_feature_bool.pt, des_tensor.pt -> user_feature2.pt, tweet_tensor.pt -> user_feature3.pt.

**Comment by TamSiuhin** [comment]
There are some differences in the file name, for example, label.pt -> label_list.pt, category_propertities -> My_user_feature_bool.pt, des_tensor.pt -> user_feature2.pt, tweet_tensor.pt -> user_feature3.pt. By the way, I recommend you to check out our latest implementation in the [Twibot-22 repo](https://github.com/LuoUndergradXJTU/TwiBot-22/tree/master/src/RGT).

**Comment by bsexpa069380** [comment]
Thanks  that is very helpful !
